#!/usr/bin/env python3
"""
post_findings_comment.py -- turn collected DDL-validation JSON results into a
single, updated PR comment so findings are visible in the PR conversation even
when the check is green (soft / advisory mode).

Reads a JSON array of per-file result objects (as emitted by
`validate_ddl.py --json`) from a file given by --results, and upserts one PR
comment (identified by a hidden marker) via the GitHub REST API.

Stdlib only. ASCII only (the Windows runner reads files as cp1252).

Environment:
  GITHUB_TOKEN       auto-provided by Actions (needs pull-requests: write)
  GITHUB_REPOSITORY  "owner/repo"
  GITHUB_PR_NUMBER   the PR number

Exit code is always 0 -- posting a comment must never fail the (soft) job.
"""
import argparse
import json
import os
import sys
import urllib.request
import urllib.error

# Hidden HTML marker so we find and UPDATE our own comment instead of posting a
# new one on every run.
MARKER = "<!-- dq-ddl-validation-comment -->"

SEV_LABEL = {
    "critical": "CRITICAL",
    "high": "HIGH",
    "medium": "MEDIUM",
    "low": "LOW",
    "info": "INFO",
}


def _api(method, url, token, data=None):
    payload = json.dumps(data).encode("utf-8") if data is not None else None
    req = urllib.request.Request(url, data=payload, method=method)
    req.add_header("Authorization", "Bearer " + token)
    req.add_header("Accept", "application/vnd.github+json")
    if payload:
        req.add_header("Content-Type", "application/json")
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = resp.read().decode("utf-8")
        return json.loads(body) if body else {}


def build_comment(results, fail_on):
    total = sum(r.get("findings_count", 0) for r in results)
    blocking = sum(r.get("blocked_by", 0) for r in results)

    lines = [MARKER, "## Data Quality - DDL Validation (advisory)", ""]

    if total == 0:
        lines.append("No data-quality findings in the changed DDL. Nice.")
        lines.append("")
        lines.append("_Advisory check -- this never blocks the merge._")
        return "\n".join(lines)

    lines.append(
        "Found **{} finding(s)** across {} file(s) "
        "({} at or above your review threshold: {}).".format(
            total, len(results), blocking, ", ".join(fail_on)
        )
    )
    lines.append("")
    lines.append(
        "> This check is **advisory** -- the PR is not blocked. "
        "Please **fix** these or consciously accept them before merging."
    )
    lines.append("")

    for r in results:
        findings = r.get("findings", [])
        fname = os.path.basename(r.get("source_file", "") or "")
        table = r.get("table_name", "")
        header = "### `{}`".format(fname)
        if table:
            header += " -- table `{}`".format(table)
        lines.append(header)
        if not findings:
            lines.append("_No findings._")
            lines.append("")
            continue
        lines.append("")
        lines.append("| Severity | Rule | Column | Issue |")
        lines.append("|---|---|---|---|")
        for f in findings:
            sev = SEV_LABEL.get(f.get("severity", ""), f.get("severity", ""))
            col = f.get("column_name") or "-"
            title = (f.get("title") or "").replace("|", "\\|")
            lines.append(
                "| {} | `{}` | `{}` | {} |".format(
                    sev, f.get("rule_code", ""), col, title
                )
            )
        lines.append("")

    lines.append("_Generated by the Data Quality shift-left gate._")
    return "\n".join(lines)


def upsert_comment(body):
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    pr = os.environ.get("GITHUB_PR_NUMBER")
    if not (token and repo and pr):
        print("[post_findings] Missing GITHUB_TOKEN/REPOSITORY/PR_NUMBER -- "
              "printing comment to log instead:\n", file=sys.stderr)
        print(body, file=sys.stderr)
        return

    base = "https://api.github.com/repos/{}/issues/{}/comments".format(repo, pr)
    try:
        existing = _api("GET", base, token)
        mine = next((c for c in existing if MARKER in (c.get("body") or "")), None)
        if mine:
            url = "https://api.github.com/repos/{}/issues/comments/{}".format(
                repo, mine["id"])
            _api("PATCH", url, token, {"body": body})
            print("[post_findings] Updated existing PR comment.")
        else:
            _api("POST", base, token, {"body": body})
            print("[post_findings] Posted new PR comment.")
    except urllib.error.HTTPError as e:
        print("[post_findings] GitHub API error {}: {}".format(
            e.code, e.read().decode("utf-8", "replace")), file=sys.stderr)
    except Exception as e:  # never fail the soft job over a comment
        print("[post_findings] Could not post comment: {}".format(e),
              file=sys.stderr)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True,
                    help="Path to a JSON file containing an array of "
                         "validate_ddl.py --json result objects.")
    ap.add_argument("--fail-on", nargs="+", default=["critical", "high"])
    args = ap.parse_args()

    try:
        with open(args.results, "r", encoding="utf-8") as fh:
            results = json.load(fh)
    except Exception as e:
        print("[post_findings] Could not read results: {}".format(e),
              file=sys.stderr)
        sys.exit(0)

    if not isinstance(results, list):
        results = [results]

    body = build_comment(results, [s.lower() for s in args.fail_on])
    upsert_comment(body)
    sys.exit(0)


if __name__ == "__main__":
    main()
